openapi: 3.0.3
info:
  title: InfraGraph
  description: |-
    ### Overview
    InfraGraph or `infrastructure graph` defines a model-driven, vendor-neutral, standard
    interface for capturing a system of systems suitable for use in co-designing AI/HPC solutions.

    This model allows for defining physical infrastructure as a logical system of systems using graph like terminology.
    In addition to defining a logical graph, an unlimited number of different physical characteristics
    can be associated with logical endpoints.

    ### Graph Terminology
    - an infrastructure `node (vertex)` is the fundamental unit or entity within an infrastructure graph; represented as a endpoint with the following syntax:
      - a combination of a device instance name and a 0 based index and a component name and a 0 based index such as `switch.0.asic.0` and `switch.0.port.0`
    - an infrastructure `edge` is a combination of two `nodes (endpoints)` in a graph such as (`switch.0.asic.0`, `switch.0.port.0`)
    - `path` is a sequence of edges that allows for traversal through the graph such as [`server.0.npu.0`, `server.0.nic.0`, `switch.0.port.0`, `switch.0.asic.0`]

    ### Contributions
    Contributions to the API and models schema can be made in the following ways:
    - [open an issue](https://github.com/keysight/infragraph/issues) in the models repository
    - [fork the models repository](https://github.com/keysight/infragraph) and submit a PR
  version: 0.4.4
  contact:
    url: https://github.com/keysight/infragraph/issues
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: /
paths: {}
