openapi: 3.0.3
info:
  title: Fragments
  version: ^0.0.0
  description: >-
    This file should be used as a repository for fragments that will be used
    as a direct inline replacement where ever the keyword is found
components:
  schemas:
    Any:
      description: |-
        Used to assign any additional information not captured by the current schema
      type: object
      additionalProperties: true
    Named.Object:
      type: object
      required: [name]
      properties:
        name:
          description: >-
            Globally unique name of an object.
            It also serves as the primary key for arrays of objects.
          type: string
          pattern: ^[\sa-zA-Z0-9-_()><\[\]]+$
          x-field-uid: 1
          x-unique: global
    ChoiceNone:
      description: >-
        A empty container that is used to indicate a null choice.
      type: object
    Tag:
      type: object
      properties:
        endpoint:
          description: |-
            A fully qualified endpoint name
            - server.0.npu.0
            - server.6.nic.3
            - switch.2.asic.0
          type: string
          x-field-uid: 1
        name:
          type: string
          x-field-uid: 2
        value:
          type: string
          x-field-uid: 3